import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { generatePlan, getActivePlan, getTasksByDate, markTaskDone } from "../services/endpoints";
import { Sparkles, CalendarDays, Check, Clock, RefreshCw, ChevronLeft, ChevronRight } from "lucide-react";
import toast from "react-hot-toast";

const TYPE_COLOR = { study: "var(--primary)", revision: "var(--accent)", break: "var(--success)" };
const TYPE_ICON  = { study: "📚", revision: "🔄", break: "☕" };

function TaskCard({ task, onToggle }) {
  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="task-item"
      style={{ opacity: task.is_done ? 0.55 : 1 }}
    >
      <button
        onClick={() => onToggle(task)}
        style={{
          width: 22, height: 22, borderRadius: 7, flexShrink: 0,
          border: task.is_done ? "none" : "2px solid var(--border-hover)",
          background: task.is_done ? "var(--primary)" : "transparent",
          cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center",
          transition: "all 0.15s",
        }}
      >
        {task.is_done && <Check size={13} color="#fff" strokeWidth={3} />}
      </button>
      <div
        style={{ width: 10, height: 10, borderRadius: "50%", background: task.subject_color || "var(--primary)", flexShrink: 0 }}
      />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{
          fontWeight: 600, fontSize: "0.875rem",
          textDecoration: task.is_done ? "line-through" : "none",
          color: task.is_done ? "var(--text-muted)" : "var(--text-primary)",
        }}>
          {task.subject_name || "Break"}
        </div>
        {task.focus && (
          <div style={{ fontSize: "0.75rem", color: "var(--text-secondary)", marginTop: 2, lineHeight: 1.4 }}>
            {task.focus}
          </div>
        )}
      </div>
      <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 3 }}>
        <span style={{
          fontSize: "0.7rem", fontWeight: 600, padding: "2px 8px", borderRadius: 999,
          background: `${TYPE_COLOR[task.task_type]}22`, color: TYPE_COLOR[task.task_type],
        }}>
          {TYPE_ICON[task.task_type]} {task.task_type}
        </span>
        <span style={{ fontSize: "0.72rem", color: "var(--text-muted)", display: "flex", alignItems: "center", gap: 3 }}>
          <Clock size={10} /> {task.duration_hours}h
        </span>
      </div>
    </motion.div>
  );
}

export default function Planner() {
  const [plan,        setPlan]        = useState(null);
  const [tasks,       setTasks]       = useState([]);
  const [selectedDate,setSelectedDate]= useState(new Date().toISOString().split("T")[0]);
  const [generating,  setGenerating]  = useState(false);
  const [loadingTasks,setLoadingTasks]= useState(false);
  const [showConfig,  setShowConfig]  = useState(false);
  const [config, setConfig] = useState({ hours_per_day: 4, days: 14 });

  useEffect(() => { loadActivePlan(); }, []);
  useEffect(() => { if (plan) loadTasksForDate(selectedDate); }, [selectedDate, plan]);

  const loadActivePlan = async () => {
    try {
      const res = await getActivePlan();
      setPlan(res.data.data);
    } catch { /* no plan yet */ }
  };

  const loadTasksForDate = async (date) => {
    setLoadingTasks(true);
    try {
      const res = await getTasksByDate(date);
      setTasks(res.data.data || []);
    } catch { setTasks([]); }
    finally { setLoadingTasks(false); }
  };

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const res = await generatePlan({ hours_per_day: config.hours_per_day, days: config.days });
      setPlan(res.data.data);
      setShowConfig(false);
      toast.success("Study plan generated by Gemini AI! 🎉");
      loadTasksForDate(selectedDate);
    } catch (e) { toast.error(e.message || "Failed to generate plan"); }
    finally { setGenerating(false); }
  };

  const handleToggleTask = async (task) => {
    try {
      await markTaskDone(task.id, !task.is_done);
      setTasks(prev => prev.map(t => t.id === task.id ? { ...t, is_done: !t.is_done } : t));
      if (!task.is_done) toast.success("Task done! 🎯");
    } catch { toast.error("Failed to update task"); }
  };

  // Date navigation helpers
  const changeDate = (delta) => {
    const d = new Date(selectedDate);
    d.setDate(d.getDate() + delta);
    setSelectedDate(d.toISOString().split("T")[0]);
  };

  const formatDate = (dateStr) => new Date(dateStr).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" });

  const doneTasks  = tasks.filter(t => t.is_done).length;
  const totalHours = tasks.reduce((a, t) => a + t.duration_hours, 0);
  const doneHours  = tasks.filter(t => t.is_done).reduce((a, t) => a + t.duration_hours, 0);

  return (
    <div className="page-content">
      {/* Header */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 28 }}>
        <div>
          <h1 style={{ fontSize: "1.6rem", fontFamily: "var(--font-display)", fontWeight: 700 }}>AI Study Planner</h1>
          <p style={{ color: "var(--text-secondary)", marginTop: 4, fontSize: "0.9rem" }}>
            {plan ? `Plan generated ${new Date(plan.generated_at).toLocaleDateString()}` : "No active plan yet"}
          </p>
        </div>
        <button
          className="btn btn-primary"
          onClick={() => setShowConfig(true)}
          style={{ gap: 8 }}
        >
          <Sparkles size={15} /> {plan ? "Regenerate Plan" : "Generate Plan"}
        </button>
      </div>

      {/* Generate Config Modal */}
      <AnimatePresence>
        {showConfig && (
          <div className="modal-overlay" onClick={() => setShowConfig(false)}>
            <motion.div
              className="modal"
              onClick={e => e.stopPropagation()}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
            >
              <div className="modal-header">
                <h3 className="modal-title">Generate AI Study Plan</h3>
                <button className="modal-close" onClick={() => setShowConfig(false)}>✕</button>
              </div>

              <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
                <div style={{
                  padding: "12px 16px", borderRadius: 10,
                  background: "rgba(16,185,129,0.08)", border: "1px solid rgba(16,185,129,0.2)",
                  fontSize: "0.85rem", color: "var(--text-secondary)",
                }}>
                  <strong style={{ color: "var(--primary-light)" }}>✨ Gemini AI</strong> will analyze your subjects, exam dates, and topic completion to create a personalized timetable.
                </div>

                <div className="form-group">
                  <label className="form-label">Daily Study Hours</label>
                  <input
                    className="input"
                    type="number" min="1" max="16" step="0.5"
                    value={isNaN(config.hours_per_day) ? "" : config.hours_per_day}
                    onChange={e => setConfig(c => ({ ...c, hours_per_day: e.target.value === "" ? "" : parseFloat(e.target.value) }))}
                  />
                  <span style={{ fontSize: "0.75rem", color: "var(--text-muted)" }}>How many hours can you study per day?</span>
                </div>

                <div className="form-group">
                  <label className="form-label">Plan Duration (days)</label>
                  <input
                    className="input"
                    type="number" min="3" max="60"
                    value={isNaN(config.days) ? "" : config.days}
                    onChange={e => setConfig(c => ({ ...c, days: e.target.value === "" ? "" : parseInt(e.target.value) }))}
                  />
                  <span style={{ fontSize: "0.75rem", color: "var(--text-muted)" }}>How many days ahead to plan?</span>
                </div>

                <div style={{ display: "flex", gap: 10, justifyContent: "flex-end" }}>
                  <button className="btn btn-ghost" onClick={() => setShowConfig(false)}>Cancel</button>
                  <button
                    className="btn btn-primary pulse-glow"
                    onClick={handleGenerate}
                    disabled={generating}
                    style={{ minWidth: 160 }}
                  >
                    {generating ? (
                      <><div className="spinner" style={{ width: 16, height: 16, borderWidth: 2 }} /> Generating...</>
                    ) : (
                      <><Sparkles size={15} /> Generate with Gemini</>
                    )}
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {!plan ? (
        <div className="empty-state card" style={{ padding: "60px 20px" }}>
          <div style={{ fontSize: "3.5rem" }}>🤖</div>
          <div className="empty-title" style={{ fontSize: "1.2rem" }}>No study plan yet</div>
          <div className="empty-desc" style={{ maxWidth: 400 }}>
            Add your subjects first, then generate an AI-powered timetable. Gemini will create a personalized schedule based on your exam dates and difficulty levels.
          </div>
          <button className="btn btn-primary" style={{ marginTop: 20 }} onClick={() => setShowConfig(true)}>
            <Sparkles size={15} /> Generate My First Plan
          </button>
        </div>
      ) : (
        <div>
          {/* Date navigator */}
          <div className="card" style={{ marginBottom: 20, padding: "16px 24px" }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <button className="btn btn-ghost" style={{ padding: "6px 12px" }} onClick={() => changeDate(-1)}>
                <ChevronLeft size={16} />
              </button>
              <div style={{ textAlign: "center" }}>
                <div style={{ fontFamily: "var(--font-display)", fontWeight: 600, fontSize: "1.05rem" }}>
                  {formatDate(selectedDate)}
                </div>
                {selectedDate === new Date().toISOString().split("T")[0] && (
                  <span className="badge badge-primary" style={{ fontSize: "0.7rem", marginTop: 4 }}>Today</span>
                )}
              </div>
              <button className="btn btn-ghost" style={{ padding: "6px 12px" }} onClick={() => changeDate(1)}>
                <ChevronRight size={16} />
              </button>
            </div>

            {/* Day summary */}
            {tasks.length > 0 && (
              <div style={{ marginTop: 12, display: "flex", gap: 20, justifyContent: "center" }}>
                <div style={{ textAlign: "center" }}>
                  <div style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--primary-light)" }}>{doneTasks}/{tasks.length}</div>
                  <div style={{ fontSize: "0.72rem", color: "var(--text-muted)" }}>Tasks done</div>
                </div>
                <div style={{ textAlign: "center" }}>
                  <div style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--accent)" }}>{doneHours.toFixed(1)}/{totalHours.toFixed(1)}h</div>
                  <div style={{ fontSize: "0.72rem", color: "var(--text-muted)" }}>Hours done</div>
                </div>
                <div style={{ textAlign: "center" }}>
                  <div style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--success)" }}>
                    {tasks.length > 0 ? Math.round((doneTasks / tasks.length) * 100) : 0}%
                  </div>
                  <div style={{ fontSize: "0.72rem", color: "var(--text-muted)" }}>Completion</div>
                </div>
              </div>
            )}

            {tasks.length > 0 && (
              <div className="progress-bar-track" style={{ marginTop: 10 }}>
                <div className="progress-bar-fill" style={{ width: `${tasks.length > 0 ? (doneTasks / tasks.length) * 100 : 0}%` }} />
              </div>
            )}
          </div>

          {/* Tasks list */}
          {loadingTasks ? (
            <div style={{ textAlign: "center", padding: "40px 0" }}><div className="spinner" style={{ margin: "0 auto" }} /></div>
          ) : tasks.length === 0 ? (
            <div className="empty-state card">
              <div className="empty-icon">🎉</div>
              <div className="empty-title">No tasks for this day</div>
              <div className="empty-desc">Rest day or the plan doesn't cover this date. Navigate to another day.</div>
            </div>
          ) : (
            <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
              <AnimatePresence>
                {tasks.map(task => (
                  <TaskCard key={task.id} task={task} onToggle={handleToggleTask} />
                ))}
              </AnimatePresence>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
